version: "3"

services:

  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite

  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    # volumes: ['./:/var/www/html']
    volumes:
      - ./data/wordpress:/var/www/html
      - type: bind
        source: ./docker-servername.conf
        target: /etc/apache2/conf-enabled/docker-servername.conf
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite

  # FTP
  ftp:
    # optionally replace username/repo:tag with your name and image details
    image: stilliard/pure-ftpd:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      # PUBLICHOST: xxx.xxx.xxx.xxx # TODO for production stage
      FTP_USER_NAME: "sam" # TODO change to your user
      FTP_USER_PASS: "password"
      FTP_USER_HOME: "/var/www/html"
      FTP_USER_UID: 33
      FTP_USER_GID: 33
    depends_on:
      - wordpress
    volumes:
      - ./data/wordpress:/var/www/html
      - ./data/ftp:/etc/ssl/private
    ports:
      - target: 21
        published: 21
        protocol: tcp
        mode: host
      - target: 30000
        published: 30000
        protocol: tcp
        mode: host
      - target: 30001
        published: 30001
        protocol: tcp
        mode: host
      - target: 30002
        published: 30002
        protocol: tcp
        mode: host
      - target: 30003
        published: 30003
        protocol: tcp
        mode: host
      - target: 30004
        published: 30004
        protocol: tcp
        mode: host
      - target: 30005
        published: 30005
        protocol: tcp
        mode: host
      - target: 30006
        published: 30006
        protocol: tcp
        mode: host
      - target: 30007
        published: 30007
        protocol: tcp
        mode: host
      - target: 30008
        published: 30008
        protocol: tcp
        mode: host
      - target: 30009
        published: 30009
        protocol: tcp
        mode: host

networks:
  wpsite:

volumes:
  db_data:
